//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotePerformerAssistant.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NotePerformerAssistant.Resources.Strings.fr", typeof(Strings_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisir un fichier .exe.
        /// </summary>
        internal static string Configuration_ChooseExeFile {
            get {
                return ResourceManager.GetString("Configuration.ChooseExeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sombre.
        /// </summary>
        internal static string Configuration_DarkTheme {
            get {
                return ResourceManager.GetString("Configuration.DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dorico.
        /// </summary>
        internal static string Configuration_Dorico {
            get {
                return ResourceManager.GetString("Configuration.Dorico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichiers EXE.
        /// </summary>
        internal static string Configuration_ExeFile {
            get {
                return ResourceManager.GetString("Configuration.ExeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemin du fichier .exe....
        /// </summary>
        internal static string Configuration_ExePath {
            get {
                return ResourceManager.GetString("Configuration.ExePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finale.
        /// </summary>
        internal static string Configuration_Finale {
            get {
                return ResourceManager.GetString("Configuration.Finale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clair.
        /// </summary>
        internal static string Configuration_LightTheme {
            get {
                return ResourceManager.GetString("Configuration.LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choix du logiciel de notation musicale.
        /// </summary>
        internal static string Configuration_MusicSoftware {
            get {
                return ResourceManager.GetString("Configuration.MusicSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotePerformer sera automatiquement installé
        ///dans un sous-dossier.
        /// </summary>
        internal static string Configuration_NotePerformerInstall {
            get {
                return ResourceManager.GetString("Configuration.NotePerformerInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez saisir un executable !.
        /// </summary>
        internal static string Configuration_SelectExe {
            get {
                return ResourceManager.GetString("Configuration.SelectExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sibelius.
        /// </summary>
        internal static string Configuration_Sibelius {
            get {
                return ResourceManager.GetString("Configuration.Sibelius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Système.
        /// </summary>
        internal static string Configuration_SystemTheme {
            get {
                return ResourceManager.GetString("Configuration.SystemTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choix du thème de l&apos;application.
        /// </summary>
        internal static string Configuration_ThemeChoice {
            get {
                return ResourceManager.GetString("Configuration.ThemeChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Performer Assistant.
        /// </summary>
        internal static string Configuration_Title {
            get {
                return ResourceManager.GetString("Configuration.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cet écran de configuration a pour but d&apos;initialiser votre espace de travail et vos préférences..
        /// </summary>
        internal static string Configuration_WelcomeSubtitle {
            get {
                return ResourceManager.GetString("Configuration.WelcomeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue sur
        ///Note Performer Assistant.
        /// </summary>
        internal static string Configuration_WelcomeTitle {
            get {
                return ResourceManager.GetString("Configuration.WelcomeTitle", resourceCulture);
            }
        }
    }
}
